// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2771);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581959231);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"53810\":1581959237581,\"53845\":1581959237563,\"19090374\":1581959237452}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"11059398\":[1581959237450]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{679cfeba-c5fc-4828-8bf8-f6efbdcfd9a6}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581959239738");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581962839738");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1581959238");
user_pref("browser.slowStartup.averageTime", 5833);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200207195153");
user_pref("browser.startup.homepage_override.mstone", "73.0");
user_pref("browser.startup.lastColdStartupCheck", 1581959234);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581959237602");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "73.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "22a19cbbc896497788d205482488c96b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "73.0");
user_pref("extensions.lastPlatformVersion", "73.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1de41e7c-f724-40c6-bae8-84e1c017df37\",\"formautofill@mozilla.org\":\"c85e95da-2fef-43c9-98be-7cb7418bdf8a\",\"screenshots@mozilla.org\":\"53e65526-cf0b-467c-bb92-5ef7e8bef790\",\"webcompat-reporter@mozilla.org\":\"3593feee-929c-463d-8218-9294714ecb1b\",\"webcompat@mozilla.org\":\"2b67ae64-2a28-4d63-adbb-178dce097ad8\",\"default-theme@mozilla.org\":\"25a15127-c70f-44e3-b828-3617be47ed61\",\"google@search.mozilla.org\":\"7c33392d-5f47-4652-87e5-a69f7ef3af0c\",\"amazondotcom@search.mozilla.org\":\"f4c96806-0c67-4878-a41d-69124674596b\",\"bing@search.mozilla.org\":\"accef364-64e6-461d-8ded-b45489aef1c0\",\"ddg@search.mozilla.org\":\"f5db0edd-aa72-41e0-ab99-98300696435b\",\"ebay@search.mozilla.org\":\"a75445e1-e080-48a4-99a1-6ee32f14f3da\",\"twitter@search.mozilla.org\":\"ffae111e-238d-49c6-aa5a-7234cfd5b761\",\"wikipedia@search.mozilla.org\":\"44d40750-2ef8-4f69-aa9f-1d5eba5bbf93\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d215e961-fd67-40ce-a6bf-bb945de43fc3");
user_pref("security.sandbox.plugin.tempDirSuffix", "c08d97eb-d1ff-418a-b3bf-135fc3a9e3ed");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1581959228);
user_pref("toolkit.telemetry.cachedClientID", "043f7b3e-5432-4f31-98c0-689692b3b480");
user_pref("toolkit.telemetry.previousBuildID", "20200207195153");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
